const make = [
    {
        img : 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80',
        name : 'Burger',
        description : 'A hamburger, or simply burger, is a food consisting of fillings—usually a patty of ground meat, typically beef—placed inside a sliced bun or bread roll. Hamburgers are often served with cheese, lettuce, tomato, onion, pickles, bacon, or chilies. condiments such as ketchup, mustard, mayonnaise, relish, or a "special sauce", often a variation of Thousand Island dressing; and are frequently placed on sesame seed buns. A hamburger patty topped with cheese is called a cheeseburger.',
        rating : 4.5,
        price : 235,
        deliveryTime : 40,
    },
    {
        img : 'https://images.unsplash.com/photo-1604908553411-28e9c23910eb?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80',
        name : 'Chicken Sandwich',
        description : 'A chicken sandwich is a sandwich that typically consists of boneless, skinless chicken breast or thigh served between slices of bread, on a bun, or on a roll. Variations on the "chicken sandwich" include the chicken burger, chicken on a bun, chickens, hot chicken, or chicken salad sandwich.',
        rating : 4.7,
        price : 299,
        deliveryTime : 40,
    },
    {
        img : 'https://images.unsplash.com/photo-1628840042765-356cda07504e?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80',
        name : 'Pizza',
        description : 'Pizza is a dish of Italian origin consisting of a usually round, flat base of leavened wheat-based dough topped with tomatoes, cheese, and often various other ingredients, which is then baked at a high temperature, traditionally in a wood-fired oven. A small pizza is sometimes called a pizz etta. The word "pizza" first appeared in a Latin text from the town of Gaeta, then still part of the Byzantine Empire, in 997 AD; the text states that a tenant of certain property is to give the bishop of Gaeta duodecim pizze ("twelve pizzas") every Christmas Day, and another twelve every Easter Sunday.',
        rating : 4.8,
        price : 315,
        deliveryTime : 40,
    },
    {
        img : 'https://images.unsplash.com/photo-1572449043416-55f4685c9bb7?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80',
        name : 'Salad',
        description : 'A salad is a serving in a meal that includes leaf vegetables such as lettuce, spinach, or arugula. Uncooked or cold cooked vegetables that are sliced into small pieces (for example tomato or onion) are then mixed with the leaf vegetables. Some salads use cheese like Greek salad uses Feta. A salad dressing or vinaigrette is then poured on top of the vegetables. Salad dressings and vinaigrettes are a mixture of oil, herbs, spices, and flavorings. Some people also add other foods to the salad, such as croutons, bacon, chicken, grated cheese, tuna, pasta, olives, cooked potatoes, rice, or beans.',
        rating : 4.9,
        price : 140,
        deliveryTime : 40,
    },
    {
        img : 'https://images.unsplash.com/photo-1587004956875-c61776f95b10?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80',
        name : 'Milk',
        description : 'Milk is a white liquid food produced by the mammary glands of mammals. It is the primary source of nutrition for young mammals before they are able to digest solid food. Immune factors and immune-modulating components in milk contribute to milk immunity. As an agricultural product, dairy milk is collected from farm animals. In 2011, dairy farms produced around 730 million tonnes (800 million short tons) of milk[3] from 260 million dairy cows.[4] India is the worlds largest producer of milk and the leading exporter of skimmed milk powder, but it exports few other milk products.[5][6] Because there is an ever-increasing demand for dairy products within India, it could eventually become a net importer of dairy products.',
        rating : 5,
        price : 90,
        deliveryTime : 40,
    },
    {
        img : 'https://images.unsplash.com/photo-1610839872428-20b646b8879d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=580&q=80',
        name : 'Birthday Cake',
        description : 'A birthday cake is a cake eaten as part of a birthday celebration. Birthday cakes are often layer cakes with frosting served with small lit candles on top representing the celebrants age. Variations include cupcakes, cake pops, pastries, and tarts. ',
        rating : 4.4,
        price : 450,
        deliveryTime : 40,
    },
]